language: node_js
node_js:
  - "stable"

before_script:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis-ci@example.com"

after_success:
  - "[ \"$TRAVIS_BRANCH\" == \"master\" ] && npm run deploy-gh-pages"

notifications:
  slack:
    secure: f5QSFkke3kvTa0Li+PT5qgFozTmY0inw0PPWJn5FXeg+P1PGIG4ksL8ACKxtwO+repbrdrLYX9kt/AQaLnktXXvuylgI5wqt+YQYIwTP8WV91SkBVJotz4+0UxRk0O47lM/IGBSV5lU6Oon0gr8zz4PPwpZw4xjWEinWmWi+ZLo=
    on_success: change
